name: CI

on:
  push:
    branches:
      - main
      - master
      - feat/**
      - fix/**
      - chore/**
  pull_request:
  schedule:
    # Weekly Sunday 02:00 UTC scheduled run to catch stale deps
    - cron: '0 2 * * 0'

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Pre-commit (format/lint hooks)
        run: |
          pre-commit run --all-files
      - name: Lint & Type Check
        run: |
          ruff check .
          black --check .
          mypy .
      - name: Security scan (bandit)
        run: |
          bandit -q -r trading || true
      - name: Vulnerability scan (pip-audit)
        run: |
          pip-audit -s low || true
      - name: Run Unit Tests with coverage (fail under 80%)
        run: |
          pytest -m "not integration" --cov=trading --cov-report=term-missing --cov-report=xml --cov-fail-under=80
      - name: Upload coverage to Codecov
        if: ${{ always() && secrets.CODECOV_TOKEN != '' }}
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          verbose: true
        continue-on-error: true

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run Integration Tests
        run: |
          pytest -m integration -q
